version: '2'
services:
    percona-1:
        container_name: percona-1
        image: percona/percona-xtradb-cluster:5.7
        environment:
            - MYSQL_DATABASE=test_db
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=testpassword
            - MYSQL_ROOT_PASSWORD=rootpassword
        ports:
            - "3306:3306"

    percona-2:
        container_name: percona-2
        image: percona/percona-xtradb-cluster:5.7
        environment:
            - MYSQL_DATABASE=test_db
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=testpassword
            - MYSQL_ROOT_PASSWORD=rootpassword
        ports:
            - "3307:3306"

    percona-3:
        container_name: percona-3
        image: percona/percona-xtradb-cluster:5.7
        environment:
            - MYSQL_DATABASE=test_db
            - MYSQL_USER=testuser
            - MYSQL_PASSWORD=testpassword
            - MYSQL_ROOT_PASSWORD=rootpassword
        ports:
            - "3308:3306"

    pmm-server:
        container_name: pmm-server
        image: percona/pmm-server:latest
        restart: always
        environment:
           - SERVER_USER=admin
           - SERVER_PASSWORD=pmm_password
           - METRICS_RETENTION=720h
           - METRICS_MEMORY=4194304
           - METRICS_RESOLUTION=1s
           - QUERIES_RETENTION=30
        ports:
          - '81:80'
